spring:
  application:
    name: configdemo

  config:
    import: optional:configserver:http://localhost:8898

  profiles:
    active: dev #${spring.profiles.active}  #dev

management:
  endpoints:
    web:
      exposure:
        include: refresh



build:
  id: ${ID}
  version: ${VERSION}
  name: ${NAME}


