build:
  id: 101   #can also do ${ID}, so that dont handcode and get from env(even though @Value gets from env itslef)
            #good for setting client secrets etc.


  version: 1.2.3
  name: "Native Dev-Production-Build 123"
  type: "Native Development Build"


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: "*"